GET http://localhost:3000/tax-payer/search/7018016325 HTTP/1.1


###
GET http://localhost:3000/tax-payer/nbo/id/6399782 HTTP/1.1


###
GET http://localhost:3000/tax-payer/nbo/inn/7018016325 HTTP/1.1\


###
GET http://localhost:3000/tax-payer/bfo/id/6399782 HTTP/1.1


###
GET http://localhost:3000/tax-payer/bfo/inn/7018016325 HTTP/1.1


###